### ISSUE TITLE
Atom type "free" not supported and breaks decoding

### ISSUE THREAD

**Issue by drogatkin** [soiaf/Java-Apple-Lossless-decoder#2]
It seems very common atom in many files and action should be just skipping it.  See my code in MediaChest for that

} else if (atom.signature == SKIPATOMTYPE || atom.signature == FREEATOMTYPE
                    || atom.signature == WIDEATOMTYPE) {
                atom.toNextAtom();
            }

**Comment by soiaf** [comment]
Thanks for letting me know that you've encountered this problem. Do you have a small sample file that demonstrates the issue so I can confirm a possible fix?

**Comment by drogatkin** [comment]
Unfortunately all my samples > 29MB due lossless nature, so I can't attach them. If you have some ftp server then I could try to upload. Here is my patch, but it isn't robust enough but still works for me.

diff --git a/com/beatofthedrum/alacdecoder/DemuxUtils.java b/com/beatofthedrum/alacdecoder/DemuxUtils.java
index 740b68c..639e189 100644
--- a/com/beatofthedrum/alacdecoder/DemuxUtils.java
+++ b/com/beatofthedrum/alacdecoder/DemuxUtils.java
@@ -861,9 +861,10 @@
                read_chunk_iods(qtmovie, sub_chunk_len);
            }
            else
-           {
-           {  
              System.err.println("(moov) unknown chunk id: " + SplitFourCC(sub_chunk_id));
-               return 0;
-               read_chunk_mvhd(qtmovie, sub_chunk_len);
- ```
            //return 0;
      }
  
      size_remaining -= sub_chunk_len;
  ```

**Comment by drogatkin** [comment]
read_chunk_mvhd actually does just skipping so I recommend to reuse it for the purpose with possibly more attractive name.

**Comment by soiaf** [comment]
Perhaps you could tell me what software package you used to produce these files in the first place? It's not that this will be difficult to fix, merely that I'd like to have a way to prove the fix - and I'm concerned I haven't seen files before showing this issue - maybe its a (relatively) new version of iTunes?
If you wish to email me, my email address is beatofthedrum@gmail.com
Thanks again for the report.

**Comment by soiaf** [comment]
This should be fixed now, thanks a lot for the report.
